name: Comentar no PR o diff das specs
on: 
  push:
    branches:
      - "main"
jobs:
  list_diff:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.job1.outputs }}
    steps:
      - uses: actions/checkout@v3
      - name: Realizar o diff entre arquivos
        id: job1
        uses: oasdiff/oasdiff-action/diff@main
        env:
          GITHUB_TOKEN: ${{ secrets.OASDIFF_TOKEN }}
        with:
          base: './swagger-apis/automatic-payments/1.0.0-beta.1.yml'
          revision: './swagger-apis/automatic-payments/1.0.0-beta.2.yml'
          
  comment_diff:
    runs-on: ubuntu-latest
    needs: list_diff
    steps:
     - name: Criar o comentário no PR
       uses: mshick/add-pr-comment@v2
       env:
        GITHUB_TOKEN: ${{ secrets.OASDIFF_TOKEN }}       
       with:
         message: |
           ${{ steps.job1.outputs.output1 }}

