name: Verificações na especificação
on: 
  pull_request:
    branches:
      - "main"
jobs:
  oas_diff_job:
    runs-on: ubuntu-latest
    name: Diff entre versões
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: Diff entre as versões
          id: diff
          uses: oasdiff/oasdiff-action/diff@main
          env:
            GITHUB_TOKEN: ${{ secrets.OASDIFF_TOKEN }}
          with:
            base: './swagger-apis/automatic-payments/1.0.0-beta.1.yml'
            revision: './swagger-apis/automatic-payments/1.0.0-beta.2.yml'
            format: 'text'
  oas_diff_breaking_changes_job:
    runs-on: ubuntu-latest
    name: A job to test OpenAPI Spec breaking changes
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Breaking changes action
        id: breaking_changes
        uses: oasdiff/oasdiff-action/breaking@test_output
        env:
          GITHUB_TOKEN: ${{ secrets.OASDIFF_TOKEN }}
        with:
          base: ./swagger-apis/automatic-payments/1.0.0-beta.1.yml
          revision: ./swagger-apis/automatic-payments/1.0.0-beta.2.yml
          fail-on-diff: false
  oas_diff_changelog_tag_job:
    runs-on: ubuntu-latest
    name: A job to test tag release of OpenAPI Spec changelog action
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Running OpenAPI Spec changelog tag action
        id: test_changelog
        uses: oasdiff/oasdiff-action/changelog@main
        env:
          GITHUB_TOKEN: ${{ secrets.OASDIFF_TOKEN }}
        with:
          base: ./swagger-apis/automatic-payments/1.0.0-beta.1.yml
          revision: ./swagger-apis/automatic-payments/1.0.0-beta.2.yml