name: Comentar no PR o diff das specs
on: 
  pull_request:
    branches:
      - "main"
jobs:
  list_diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.job1.outputs.test }}
    steps:
    - name: Running OpenAPI Spec diff action
      id: oasdiff
      uses: oasdiff/oasdiff-action/diff@main
      with:
        base: api-docs.base.json
        revision: api-docs.json
        fail-on-diff: 'false'

    - name: Post oasdiff report
      if: ${{ steps.oasdiff.outputs.diff}}
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          <!-- bot:oasdiff -->
          Found these breaking changes on the public API:

          ```
          ${{ steps.oasdiff.outputs.diff }}
          ```
        edit-mode: create

