name: optic
on:
  pull_request:
  push:
    branches:
      - "main"
 
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
             ./swagger-apis/payments/
 
      - name: Install Optic
        run: npm install --location global @useoptic/optic
 
      - name: Run Optic
        env:
          OPTIC_TOKEN: ${{ secrets.OPTIC_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: optic diff 4.0.0.yml 4.1.0.yml --check